#para-NHPP-simulation
COS_Path = paste0(dirname(rstudioapi::getSourceEditorContext()$path),"/simMethod/COS_r.R")
print("Load COS NHPP Simulation module")
# print(COS_Path)
source(COS_Path)
GSm_Path = paste0(dirname(rstudioapi::getSourceEditorContext()$path),"/simMethod/GS-_r.R")
print("Load GS- NHPP simulation module")
# print(GS-_Path)
source(GSm_Path)
GSp_Path = paste0(dirname(rstudioapi::getSourceEditorContext()$path),"/simMethod/GS+_r.R")
print("Load GS+ NHPP Simulation module")
# print(GSp_Path)
source(GSp_Path)
RGS_Path = paste0(dirname(rstudioapi::getSourceEditorContext()$path),"/simMethod/RGS_r.R")
print("Load RGS NHPP simulation module")
# print(RGS_Path)
source(RGS_Path)

#nonpara-NHPP-simulation
Tim_Path = paste0(dirname(rstudioapi::getSourceEditorContext()$path),"/simMethod/TimTra_r.R")
print("Load Timtra NHPP Simulation module")
# print(Tim_Path)
source(Tim_Path)
Int_Path = paste0(dirname(rstudioapi::getSourceEditorContext()$path),"/simMethod/IntGen_r.R")
print("Load IntGen NHPP simulation module")
# print(Int_Path)
source(Int_Path)
Ord_Path = paste0(dirname(rstudioapi::getSourceEditorContext()$path),"/simMethod/OrdSta_r.R")
print("Load OrdSta NHPP Simulation module")
# print(Ord_Path)
source(Ord_Path)
Thi_Path = paste0(dirname(rstudioapi::getSourceEditorContext()$path),"/simMethod/ThiArr_r.R")
print("Load Thi NHPP simulation module")
# print(Thi_Path)
source(Thi_Path)

ThiInt_Path = paste0(dirname(rstudioapi::getSourceEditorContext()$path),"/simMethod/ThiInt_r.R")
print("Load ThiInt NHPP simulation module")
# print(ThiInt_Path)
source(ThiInt_Path)